language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python visual_looming/test.py
before_script:
  - sudo apt-get install libopencv-dev python-opencv
  - sudo apt-get update
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
