language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python visual_looming/tests.py

before_script:
  - wget opencv_python‑3.1.0‑cp27‑cp27m‑win_amd64.whl
