language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python visual_looming/tests.py
before_script:
  - sudo add-apt-repository python-opencv
  - sudo apt-get update
